---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: applications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
      annotations:
        sidecar.aws.signing-proxy/inject: "true"
        #sidecar.aws.signing-proxy/host: "backend-canary-store-0bb73f5d62694926a.7d67968.vpc-lattice-svcs.us-west-2.on.aws"
        sidecar.aws.signing-proxy/name: "vpc-lattice-svcs"
        sidecar.aws.signing-proxy/region: "us-west-2"
        sidecar.aws.signing-proxy/unsigned-payload: "true"        
        sidecar.aws.signing-proxy/scheme: "https"        
    spec: 
      serviceAccountName: aws-sigv4-proxy
      containers:          
        - name: go  
          image: 937351930975.dkr.ecr.us-west-2.amazonaws.com/k8s-frontend:lattice
          imagePullPolicy: Always   
          env:
            - name: AWS_REGION
              value: us-west-2
            - name: DATASTORE_SERVICE_PROTOCOL
              value: http
            - name: DATASTORE_SERVICE_URL
              value: localhost:8005
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          resources:
            requests:
              cpu: "50m"
              memory: "128Mi"
          livenessProbe:
            httpGet: 
              path: /live
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3            
          readinessProbe:
            httpGet: 
              path: /ready
              port: 3000
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
            failureThreshold: 3        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
  namespace: applications
spec:
  type: ClusterIP  
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: frontend

