---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: Gateway
metadata:
  name: eks-multi-cluster
  annotations:
    application-networking.k8s.aws/lattice-vpc-association: "true"  
spec:
  gatewayClassName: amazon-vpc-lattice
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All