---
apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: backend-canary
  namespace: apps
spec:
  parentRefs:
  - name: eks-multi-cluster
    sectionName: http 
  rules:  
  - backendRefs:  
    - name: datastore-v1-svc
      kind: Service
      port: 3000
      namespace: apps
    matches:
    - path:
        type: PathPrefix
        value: /popular
  - backendRefs:  
    - name: datastore-v1-svc
      kind: Service
      port: 3000
      namespace: apps
      weight: 50
    - name: datastore-v2-svc
      kind: Service
      port: 3000
      namespace: apps      
      weight: 50
    matches:
    - path:
        type: PathPrefix
        value: /summary

       