apiVersion: gateway.networking.k8s.io/v1alpha2
kind: HTTPRoute
metadata:
  name: backend
  namespace: apps
spec:
  parentRefs:
  - name: eks-multi-cluster
    sectionName: http 
  rules:
  - backendRefs:  
    - name: datastore-svc
      kind: Service
      port: 3000
      namespace: default
    matches:
    - path:
        type: PathPrefix
        value: /popular
